apiVersion: apps/v1
kind: Deployment
metadata:
  name: riverli-blog
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: riverli-blog
  template:
    metadata:
      labels:
        app: riverli-blog
    spec:
      # 👇 加上这段，告诉 K8s 用刚才创建的 ghcr-secret 
      #kubectl create secret docker-registry ghcr-secret \
      #  --docker-server=ghcr.io \
      #  --docker-username=strive9930 \
      #  --docker-password=token密钥 \
      #  -n default
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: blog-api
          # 🌟 这行就是舞台的中心！现在写的是 :latest，等下 Jenkins 就会把它改成 :v10
          image: ghcr.io/strive9930/riverli-blog-api:v45
          ports:
            - containerPort: 8080
          env:
            - name: ConsulConfig__Address
              value: "http://consul-server:8500"
---
apiVersion: v1
kind: Service
metadata:
  name: blog-service
  namespace: default
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: riverli-blog